name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag opthub/hypervolume:latest
    - name: Test the Docker image
      run: |
        time cat population.2obj.txt | docker run --rm -i opthub/hypervolume:latest
        time cat population.2obj.constr.txt | docker run --rm -i opthub/hypervolume:latest
        time cat population.3obj.txt | docker run --rm -i opthub/hypervolume:latest
